import type { SceneId } from "@/data/scenes";
import type { VisualState } from "@/store/cinematicStore";

export const INITIAL_VISUAL_STATE: VisualState = {
  cameraX: 0,
  cameraY: 0.12,
  cameraZ: 6.4,
  objectScale: 0.14,
  objectX: 0,
  objectY: 0,
  objectZ: -1.6,
  objectRotationX: 0,
  objectRotationY: 0,
  objectRotationZ: 0,
  emissiveIntensity: 0.35,
  fragmentSpread: 0,
  particleDrift: 0,
  torusVisible: 0,
};

export const SCENE_VISUAL_KEYFRAMES: Record<SceneId, VisualState> = {
  signal: {
    cameraX: 0,
    cameraY: 0.1,
    cameraZ: 6.2,
    objectScale: 0.14,
    objectX: 0,
    objectY: 0,
    objectZ: -1.8,
    objectRotationX: 0,
    objectRotationY: 0.2,
    objectRotationZ: 0,
    emissiveIntensity: 0.35,
    fragmentSpread: 0,
    particleDrift: 0.2,
    torusVisible: 0,
  },
  spark: {
    cameraX: 0.4,
    cameraY: 0.18,
    cameraZ: 5.1,
    objectScale: 0.58,
    objectX: -0.15,
    objectY: -0.1,
    objectZ: 0,
    objectRotationX: 0.15,
    objectRotationY: 1.4,
    objectRotationZ: 0.05,
    emissiveIntensity: 1.15,
    fragmentSpread: 0,
    particleDrift: 0.6,
    torusVisible: 0,
  },
  chaos: {
    cameraX: -0.25,
    cameraY: 0.05,
    cameraZ: 4.1,
    objectScale: 0.46,
    objectX: 0.1,
    objectY: 0.05,
    objectZ: 0.35,
    objectRotationX: 0.75,
    objectRotationY: 2.6,
    objectRotationZ: 0.45,
    emissiveIntensity: 0.9,
    fragmentSpread: 1,
    particleDrift: 1.4,
    torusVisible: 0,
  },
  structure: {
    cameraX: 0.05,
    cameraY: 0.22,
    cameraZ: 5.05,
    objectScale: 0.64,
    objectX: 0,
    objectY: 0,
    objectZ: 0,
    objectRotationX: 0,
    objectRotationY: 0,
    objectRotationZ: 0,
    emissiveIntensity: 0.78,
    fragmentSpread: 0.12,
    particleDrift: 0.35,
    torusVisible: 0,
  },
  system: {
    cameraX: -0.35,
    cameraY: 0.14,
    cameraZ: 4.55,
    objectScale: 0.74,
    objectX: 0.2,
    objectY: 0,
    objectZ: 0,
    objectRotationX: 0,
    objectRotationY: 0.55,
    objectRotationZ: 0,
    emissiveIntensity: 0.95,
    fragmentSpread: 0,
    particleDrift: 0.25,
    torusVisible: 0.85,
  },
  launch: {
    cameraX: 0,
    cameraY: 0.08,
    cameraZ: 6.1,
    objectScale: 0.68,
    objectX: 0,
    objectY: 0,
    objectZ: -0.25,
    objectRotationX: 0,
    objectRotationY: 0,
    objectRotationZ: 0,
    emissiveIntensity: 1.05,
    fragmentSpread: 0,
    particleDrift: 0.15,
    torusVisible: 1,
  },
};

