import type { SceneId } from "@/data/scenes";
import type { VisualState } from "@/store/cinematicStore";

export const INITIAL_VISUAL_STATE: VisualState = {
  cameraX: 0,
  cameraY: 0.12,
  cameraZ: 6.5,
  objectScale: 0.12,
  objectX: 0,
  objectY: 0,
  objectZ: -1.85,
  objectRotationX: 0,
  objectRotationY: 0,
  objectRotationZ: 0,
  emissiveIntensity: 0.28,
  fragmentSpread: 0,
  particleDrift: 0.08,
  torusVisible: 0,
};

export const SCENE_VISUAL_KEYFRAMES: Record<SceneId, VisualState> = {
  signal: {
    cameraX: 0,
    cameraY: 0.1,
    cameraZ: 5.95,
    objectScale: 0.16,
    objectX: 0,
    objectY: 0,
    objectZ: -1.65,
    objectRotationX: 0,
    objectRotationY: 0.15,
    objectRotationZ: 0,
    emissiveIntensity: 0.38,
    fragmentSpread: 0,
    particleDrift: 0.28,
    torusVisible: 0,
  },
  spark: {
    cameraX: 0.5,
    cameraY: 0.2,
    cameraZ: 4.95,
    objectScale: 0.62,
    objectX: -0.12,
    objectY: -0.08,
    objectZ: -0.05,
    objectRotationX: 0.12,
    objectRotationY: 1.55,
    objectRotationZ: 0.04,
    emissiveIntensity: 1.2,
    fragmentSpread: 0,
    particleDrift: 0.72,
    torusVisible: 0,
  },
  chaos: {
    cameraX: -0.2,
    cameraY: 0.04,
    cameraZ: 3.85,
    objectScale: 0.48,
    objectX: 0.08,
    objectY: 0.04,
    objectZ: 0.42,
    objectRotationX: 0.82,
    objectRotationY: 2.75,
    objectRotationZ: 0.5,
    emissiveIntensity: 0.95,
    fragmentSpread: 1,
    particleDrift: 1.5,
    torusVisible: 0,
  },
  structure: {
    cameraX: 0,
    cameraY: 0.2,
    cameraZ: 5.15,
    objectScale: 0.66,
    objectX: 0,
    objectY: 0,
    objectZ: 0,
    objectRotationX: 0,
    objectRotationY: 0,
    objectRotationZ: 0,
    emissiveIntensity: 0.82,
    fragmentSpread: 0.05,
    particleDrift: 0.32,
    torusVisible: 0,
  },
  system: {
    cameraX: 0,
    cameraY: 0.12,
    cameraZ: 4.65,
    objectScale: 0.76,
    objectX: 0,
    objectY: 0,
    objectZ: 0,
    objectRotationX: 0,
    objectRotationY: 0.35,
    objectRotationZ: 0,
    emissiveIntensity: 0.98,
    fragmentSpread: 0,
    particleDrift: 0.22,
    torusVisible: 1,
  },
  launch: {
    cameraX: 0,
    cameraY: 0.06,
    cameraZ: 6.35,
    objectScale: 0.7,
    objectX: 0,
    objectY: 0,
    objectZ: -0.35,
    objectRotationX: 0,
    objectRotationY: 0,
    objectRotationZ: 0,
    emissiveIntensity: 1,
    fragmentSpread: 0,
    particleDrift: 0.12,
    torusVisible: 1,
  },
};
